In [1]:
# imports
import numpy as np
import string
import plotly.graph_objects as go

# question 1

In [2]:
alpha_list = string.ascii_lowercase

str_ = 'cfilorux'
str_list = [alpha_list[i] for i, char in enumerate(alpha_list) if (i+1)%3==0]
str_ = ''.join(str_list)
print(str_)

str_ = 'vxz'
alpha_list_end = alpha_list[alpha_list.index('v'):]
str_list = [alpha_list_end[i] for i, char in enumerate(alpha_list_end) if (i)%2==0]
str_ = ''.join(str_list)
print(str_)

str_ = 'zxvt'
alpha_list_end = alpha_list[alpha_list.index('t'):][::-1]
str_list = [alpha_list_end[i] for i, char in enumerate(alpha_list_end) if (i)%2==0]
str_ = ''.join(str_list)
print(str_)

cfilorux
vxz
zxvt


# question 2

In [3]:
str_ = " XHEC DataScience for Business "
str_ = str_.lower()
print('lower case :' ,str_ )
str_ = str_.strip()
print('remove spaces :' , str_)
str_ = str_.replace('e','E')
print('remove spaces :' , str_)

lower case :  xhec datascience for business 
remove spaces : xhec datascience for business
remove spaces : xhEc datasciEncE for businEss


# question 3

In [4]:
print("{:.9f}".format(np.pi))

3.141592654


# question 4

In [5]:
s = "HelLo WorLd!!"

# normalize characters
s = s.lower()

# where to store count chars
dict_characters = {}

for current_char in s:
    # check if already there
    if current_char in dict_characters.keys():
        continue
    
    # count occurences
    dict_characters[current_char] = 0
    for c in s:
        # increment count
        if c == current_char:
            dict_characters[current_char] += 1


# result
print(dict_characters)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1, '!': 2}


# question 5

In [6]:
nbr = 0.1 + 100 - 100
print('compare using == : ' , nbr==0.1)
# 0.1 is not an int so python only store an approximation of it and give us a round value of it thus when doing computation with it we get a false result due to rounding errors 
print('compare using np.isclose : ', np.isclose([nbr], [0.1], rtol=1e-5)[0])


compare using == :  False
compare using np.isclose :  True


# question 6 : 

In [7]:
# create a list of all square numbers between 1 and 121

def is_square(nbr):
    return np.isclose([np.sqrt(nbr)], [int(np.sqrt(nbr))], rtol=1e-5)[0]

sq_list = [i for i in range(1,122) if is_square(i) ]
sq_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

# question 7 : 

In [8]:
# create array containing integers from 2 to 14 by step of 3

list_ = np.arange(2,15,3)
print(list_)
# Create an array with 15 equispaced valued from 0 to 1 included 
list_ = np.linspace(0,1,15)
print(list_)

[ 2  5  8 11 14]
[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# question 8

In [9]:

def serie_term(k):
    sqr_k = k**2
    return 4 * sqr_k /( 4 * sqr_k -1)


In [10]:
%%timeit
# using loop 

prod_loop = 2 
for k in range(1,1000000):
    prod_loop = prod_loop * serie_term(k)


760 ms ± 300 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%%timeit
# compute a product serie using numpy 

x = np.arange(1,1000000)
prod_numpy = 2*np.prod(serie_term(x))



20.5 ms ± 5.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
# numpy is way more faster since it use vectorization and is faster to compute the product serie

# question 9 : 

In [13]:
# Compute the dot product of np.arange(5) and np.ones(5)
a = np.arange(5)
b = np.ones(5)
print(a.dot(b))
print(a.shape)
# a have 5 rows with  1 column 
print(a.transpose())
# transpose of a 1D array is still a 1D array 

10.0
(5,)
[0 1 2 3 4]


# question 10

In [14]:
M = np.arange(12).reshape(2, 6)

- convert a matrix (rows=1, cols=12) to a matrix (rows=2, cols=6)

In [15]:
M[:, ::3]

array([[0, 3],
       [6, 9]])

- slice the columns of ``M`` with a step of 3

In [16]:
np.arange(3) * np.arange(4)[:, None]

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

- this compute the **outer product** of ``np.arange(3)`` and ``np.arange(4)``

# question 11

In [17]:
# create random matrix
M = np.random.uniform(low=-1, high=1, size=(5, 6))

print("initial matrix \n {}".format(M))

# operation
for i in range(0, 5, 2):
    M[:, i] -= 2 * M[:, i+1]

# print result
print("final matrix \n {}".format(M))

initial matrix 
 [[ 0.49456836  0.95960302  0.15214751  0.49679556 -0.77819433 -0.91466298]
 [ 0.15365816  0.65392365  0.91708404  0.42112998  0.64841468  0.28688436]
 [ 0.17754314 -0.88324377 -0.01893759 -0.85620489 -0.86776493  0.42198482]
 [-0.44231582  0.20723764 -0.42920643  0.04497584 -0.24444662  0.56388402]
 [-0.51876073 -0.22972441  0.1785028   0.52414265 -0.27502287 -0.98276215]]
final matrix 
 [[-1.42463767  0.95960302 -0.84144361  0.49679556  1.05113163 -0.91466298]
 [-1.15418915  0.65392365  0.07482407  0.42112998  0.07464596  0.28688436]
 [ 1.94403067 -0.88324377  1.6934722  -0.85620489 -1.71173456  0.42198482]
 [-0.85679111  0.20723764 -0.5191581   0.04497584 -1.37221465  0.56388402]
 [-0.05931191 -0.22972441 -0.86978249  0.52414265  1.69050142 -0.98276215]]


# question 12

In [18]:
# neg value to zero
M = M * (M >= 0)

print("non negative \n {}".format(M))

# mean rows
mean = np.mean(M, axis=1)

M -= mean[:, None]

print("M minus mean \n {}".format(M))

non negative 
 [[-0.          0.95960302 -0.          0.49679556  1.05113163 -0.        ]
 [-0.          0.65392365  0.07482407  0.42112998  0.07464596  0.28688436]
 [ 1.94403067 -0.          1.6934722  -0.         -0.          0.42198482]
 [-0.          0.20723764 -0.          0.04497584 -0.          0.56388402]
 [-0.         -0.         -0.          0.52414265  1.69050142 -0.        ]]
M minus mean 
 [[-0.4179217   0.54168132 -0.4179217   0.07887386  0.63320993 -0.4179217 ]
 [-0.25190134  0.40202232 -0.17707727  0.16922865 -0.17725538  0.03498302]
 [ 1.26744939 -0.67658128  1.01689092 -0.67658128 -0.67658128 -0.25459647]
 [-0.13601625  0.07122139 -0.13601625 -0.09104041 -0.13601625  0.42786777]
 [-0.36910734 -0.36910734 -0.36910734  0.1550353   1.32139407 -0.36910734]]


# question 13

In [19]:
M = np.random.uniform(low=-1, high=1, size=(5, 10))

G = M.T @ M
eigen_val_G, _ = np.linalg.eig(G)

# semi definte positive
print("G is semi-definte positive: {0}".format(all(eigen_val_G > 0)))

# rank
print("rank of G: {}".format(np.linalg.matrix_rank(G)))

# euclidean norm
print("euclidean norm of G: {}".format(np.linalg.norm(G)))

# Schatten 2-norm
print("Schatten 2-norm of G: {}".format(np.linalg.norm(G, ord="nuc")))

# std of cols
std_G = np.std(G, axis=0)
print("std of cols: \n {}".format(std_G))

G is semi-definte positive: False
rank of G: 5
euclidean norm of G: 8.497290600806343
Schatten 2-norm of G: 16.95924310826983
std of cols: 
 [0.55482937 0.58249879 0.68066922 0.5202255  1.1354289  0.84402891
 0.68480259 1.00834859 0.74013295 0.87707662]


# question 14

In [20]:
# params
interval = [-1, 2]
nb_points = 100
x = np.linspace(*interval, nb_points)

# plots
fig = go.Figure(data=[
    go.Scatter(
        x=x,
        y=x ** d,
        mode="lines",
        name=f"x^{d}"
    )
for d in [2, 3, 4]])


fig.update_layout(
    title="Plots x^d for d in {2, 3, 4}",
    xaxis_title="x",
    yaxis_title="y",
)

fig.show()

# question 15

In [21]:
# Create an array with integers 1, 3, ..., 19
a = np.arange(1,20)
print(a)
# Subtract its mean to it 
a = a - np.mean(a)
print('a-mean(a) : ', a)
print('----')
# Create an array with 3 lines and 4 columns, such that arr[i, j] = 4 * i + j
a = np.arange(3*4).reshape(3,4)
print('a of shape 3,4')
print(a)

# transform each element (i,j) of a to 4*i + j
def transform (x):
    i,j =  np.where(a == x)
    i,j = i[0],j[0]
    return 5 * i  + j
myfunc_vec = np.vectorize(transform)

result = myfunc_vec(a)
print('transform')
print(result)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a-mean(a) :  [-9. -8. -7. -6. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.  6.  7.  8.
  9.]
----
a of shape 3,4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transform
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


# question 16

In [22]:
# subtract its column wise mean to it 
result = result - np.mean(result, axis=0)
print(result)

[[-5. -5. -5. -5.]
 [ 0.  0.  0.  0.]
 [ 5.  5.  5.  5.]]


In [23]:
# Subtract its row wise mean to it
result = result - np.mean(result, axis=1)[:,None]

# question 17 

In [24]:

x = np.array([np.arange(5)])
a = np.repeat(x, [3], axis=0)
print(a)
x = np.array([np.arange(3)])
b = np.repeat(x, [5], axis=0).T
print(b)
print('result')
print(a*b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
result
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


# question 18

In [25]:
a = 1000
print("adress a: {}".format(id(a)))

b = 1000
print("adress b: {}".format(id(b)))

c = a
print("adress c: {}".format(id(c)))

a += 1

print("val a: {0} \nval c: {1}".format(a, c))


adress a: 1738232856496
adress b: 1738232856432
adress c: 1738232856496
val a: 1001 
val c: 1000


- cette opération n'affecte pas la var ``c`` car les vars n'ont
pas la même adress mémoire

# question 19

In [26]:
a =  np.array([0, 1])
print("adress a: {}".format(id(a)))

b =  np.array([0, 1])
print("adress b: {}".format(id(b)))

c = a
print("adress c: {}".format(id(c)))

a += 1

print("val a: {0} \nval c: {1}".format(a, c))

adress a: 1738232882800
adress b: 1738232881680
adress c: 1738232882800
val a: [1 2] 
val c: [1 2]



- cette opération affecte la var ``c`` car les vars ont
 la même adress mémoire

# question 20

In [27]:
# create vars
var_1 = 1
var_2 = 1

print("var_1 == var_2: {}".format(var_1 == var_2))
print("var_1 is var_2: {}".format(var_1 is var_2))

var_1 == var_2: True
var_1 is var_2: True


In [28]:
# create vars
var_1 = 1000
var_2 = 1000

print("var_1 == var_2: {}".format(var_1 == var_2))
print("var_1 is var_2: {}".format(var_1 is var_2))

var_1 == var_2: True
var_1 is var_2: False


- dans le 1er cas les deux vars ont même adresse
- dans le 2ème cas les deux vars n'ont pas la même adresse
- ``==`` fait un check sur les valeurs des variable, cependant ``is`` fait check sur l'adresse