In [ ]:
# question 1 : 
import string
alpha_list = string.ascii_lowercase

str_ = 'cfilorux'
str_list = [alpha_list[i] for i, char in enumerate(alpha_list) if (i+1)%3==0]
str_ = ''.join(str_list)
print(str_)

str_ = 'vxz'
alpha_list_end = alpha_list[alpha_list.index('v'):]
str_list = [alpha_list_end[i] for i, char in enumerate(alpha_list_end) if (i)%2==0]
str_ = ''.join(str_list)
print(str_)

str_ = 'zxvt'
alpha_list_end = alpha_list[alpha_list.index('t'):][::-1]
str_list = [alpha_list_end[i] for i, char in enumerate(alpha_list_end) if (i)%2==0]
str_ = ''.join(str_list)
print(str_)

cfilorux
vxz
zxvt


In [ ]:
# question 2 : 
str_ = " XHEC DataScience for Business "
str_ = str_.lower()
print('lower case :' ,str_ )
str_ = str_.strip()
print('remove spaces :' , str_)
str_ = str_.replace('e','E')
print('remove spaces :' , str_)

lower case :  xhec datascience for business 
remove spaces : xhec datascience for business
remove spaces : xhEc datasciEncE for businEss


In [ ]:
# question 5
nbr = 0.1 + 100 - 100
print('compare using == : ' , nbr==0.1)
# 0.1 is not an int so python only store an approximation of it and give us a round value of it thus when doing computation with it we get a false result due to rounding errors 
print('compare using np.isclose : ', np.isclose([nbr], [0.1], rtol=1e-5)[0])


compare using == :  False
compare using np.isclose :  True


In [ ]:
# question 6 : 
# create a list of all square numbers between 1 and 121
import numpy as np 
def is_square(nbr):
    return np.isclose([np.sqrt(nbr)], [int(np.sqrt(nbr))], rtol=1e-5)[0]

sq_list = [i for i in range(1,122) if is_square(i) ]
sq_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

In [ ]:
# question 7 : 
# create array containing integers from 2 to 14 by step of 3
import numpy as np
list_ = np.arange(2,15,3)
print(list_)
# Create an array with 15 equispaced valued from 0 to 1 included 
list_ = np.linspace(0,1,15)
print(list_)

In [ ]:
# question 8
import numpy as np
def serie_term(k):
    sqr_k = k**2
    return 4 * sqr_k /( 4 * sqr_k -1)



In [ ]:
%%timeit
# using loop 

prod_loop = 2 
for k in range(1,1000000):
    prod_loop = prod_loop * serie_term(k)


780 ms ± 50.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
# compute a product serie using numpy 
import numpy as np

x = np.arange(1,1000000)
prod_numpy = 2*np.prod(serie_term(x))



21.3 ms ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# numpy is way more faster since it use vectorization and is faster to compute the product serie

In [ ]:
# question 9 : 
# Compute the dot product of np.arange(5) and np.ones(5)
a = np.arange(5)
b = np.ones(5)
print(a.dot(b))
print(a.shape)
# a have 5 rows with  1 column 
print(a.transpose())
# transpose of a 1D array is still a 1D array 

10.0
(5,)
[0 1 2 3 4]


In [ ]:
# question 15
# Create an array with integers 1, 3, ..., 19
a = np.arange(1,20)
print(a)
# Subtract its mean to it 
a = a - np.mean(a)
print('a-mean(a) : ', a)
print('----')
# Create an array with 3 lines and 4 columns, such that arr[i, j] = 4 * i + j
a = np.arange(3*4).reshape(3,4)
print('a of shape 3,4')
print(a)

# transform each element (i,j) of a to 4*i + j
def transform (x):
    i,j =  np.where(a == x)
    i,j = i[0],j[0]
    return 5 * i  + j
myfunc_vec = np.vectorize(transform)

result = myfunc_vec(a)
print('transform')
print(result)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a-mean(a) :  [-9. -8. -7. -6. -5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.  6.  7.  8.
  9.]
----
a of shape 3,4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transform
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [ ]:
# question 16
# subtract its column wise mean to it 
result = result - np.mean(result, axis=0)
print(result)

[[-5. -5. -5. -5.]
 [ 0.  0.  0.  0.]
 [ 5.  5.  5.  5.]]


In [ ]:
# Subtract its row wise mean to it
result = result - np.mean(result, axis=1)[:,None]

In [ ]:
# question 17 

x = np.array([np.arange(5)])
a = np.repeat(x, [3], axis=0)
print(a)
x = np.array([np.arange(3)])
b = np.repeat(x, [5], axis=0).T
print(b)
print('result')
print(a*b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
result
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]
