In [ ]:
# 3

In [3]:
import numpy as np

print("{:.9f}".format(np.pi))

3.141592654


In [ ]:
# 4

In [7]:
s = "HelLo WorLd!!"

# normalize characters
s = s.lower()

# where to store count chars
dict_characters = {}

for current_char in s:
    # check if already there
    if current_char in dict_characters.keys():
        continue
    
    # count occurences
    dict_characters[current_char] = 0
    for c in s:
        # increment count
        if c == current_char:
            dict_characters[current_char] += 1


# result
print(dict_characters)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1, '!': 2}


In [ ]:
# 10

In [18]:
M = np.arange(12).reshape(2, 6)

- convert a matrix (rows=1, cols=12) to a matrix (rows=2, cols=6)

In [19]:
M[:, ::3]

array([[0, 3],
       [6, 9]])

- slice the columns of ``M`` with a step of 3

In [21]:
np.arange(3) * np.arange(4)[:, None]

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

- this compute the **outer product** of ``np.arange(3)`` and ``np.arange(4)``

In [ ]:
# 11

In [40]:
import numpy as np

# create random matrix
M = np.random.uniform(low=-1, high=1, size=(5, 6))

print("initial matrix \n {}".format(M))

# operation
for i in range(0, 5, 2):
    M[:, i] -= 2 * M[:, i+1]

# print result
print("final matrix \n {}".format(M))

initial matrix 
 [[ 0.62788391 -0.58189924 -0.61830938 -0.26243642 -0.81862531  0.73539436]
 [-0.96183437  0.68610483 -0.40895996 -0.20699032 -0.57516183 -0.65921041]
 [-0.57508421  0.56454598  0.66535414 -0.95466463  0.04775406 -0.12744973]
 [-0.93560325  0.21255655 -0.06032935  0.45756091  0.28514557  0.24339706]
 [-0.74590533  0.05207996  0.03028463 -0.72480112 -0.45059735 -0.96374169]]
final matrix 
 [[ 1.79168238 -0.58189924 -0.09343653 -0.26243642 -2.28941402  0.73539436]
 [-2.33404402  0.68610483  0.00502068 -0.20699032  0.74325899 -0.65921041]
 [-1.70417617  0.56454598  2.5746834  -0.95466463  0.30265352 -0.12744973]
 [-1.36071635  0.21255655 -0.97545117  0.45756091 -0.20164855  0.24339706]
 [-0.85006525  0.05207996  1.47988686 -0.72480112  1.47688603 -0.96374169]]


In [ ]:
# 12

In [41]:
# neg value to zero
M = M * (M >= 0)

print("non negative \n {}".format(M))

# mean rows
mean = np.mean(M, axis=1)

M -= mean[:, None]

print("M minus mean \n {}".format(M))

non negative 
 [[ 1.79168238 -0.         -0.         -0.         -0.          0.73539436]
 [-0.          0.68610483  0.00502068 -0.          0.74325899 -0.        ]
 [-0.          0.56454598  2.5746834  -0.          0.30265352 -0.        ]
 [-0.          0.21255655 -0.          0.45756091 -0.          0.24339706]
 [-0.          0.05207996  1.47988686 -0.          1.47688603 -0.        ]]
M minus mean 
 [[ 1.37050292 -0.42117946 -0.42117946 -0.42117946 -0.42117946  0.3142149 ]
 [-0.23906408  0.44704074 -0.2340434  -0.23906408  0.50419491 -0.23906408]
 [-0.57364715 -0.00910117  2.00103625 -0.57364715 -0.27099363 -0.57364715]
 [-0.15225242  0.06030413 -0.15225242  0.30530849 -0.15225242  0.09114464]
 [-0.50147548 -0.44939551  0.97841139 -0.50147548  0.97541055 -0.50147548]]


# 13

In [78]:
import numpy as np

M = np.random.uniform(low=-1, high=1, size=(5, 10))

G = M.T @ M
eigen_val_G, _ = np.linalg.eig(G)

# semi definte positive
print("G is semi-definte positive: {0}".format(all(eigen_val_G > 0)))

# rank
print("rank of G: {}".format(np.linalg.matrix_rank(G)))

# euclidean norm
print("euclidean norm of G: {}".format(np.linalg.norm(G)))

# Schatten 2-norm
print("Schatten 2-norm of G: {}".format(np.linalg.norm(G, ord="nuc")))

# std of cols
std_G = np.std(G, axis=0)
print("std of cols: \n {}".format(std_G))

G is semi-definte positive: False
rank of G: 5
euclidean norm of G: 9.83054876257476
Schatten 2-norm of G: 18.914595004861944
std of cols: 
 [0.99625328 0.77918634 1.03824886 0.82548917 1.39303267 0.74535491
 0.68865689 0.99316622 0.99495812 0.92347073]


# 14

In [79]:
import plotly.graph_objects as go

# params
interval = [-1, 2]
nb_points = 100
x = np.linspace(*interval, nb_points)

# plots
fig = go.Figure(data=[
    go.Scatter(
        x=x,
        y=x ** d,
        mode="lines",
        name=f"x^{d}"
    )
for d in [2, 3, 4]])


fig.update_layout(
    title="Plots x^d for d in {2, 3, 4}",
    xaxis_title="x",
    yaxis_title="y",
)

fig.show()

# 18

In [88]:
a = 1000
print("adress a: {}".format(id(a)))

b = 1000
print("adress b: {}".format(id(b)))

c = a
print("adress c: {}".format(id(c)))

a += 1

print("val a: {0} \nval c: {1}".format(a, c))


adress a: 2063831849328
adress b: 2063831848528
adress c: 2063831849328
val a: 1001 
val c: 1000


- cette opération n'affecte pas la var ``c`` car les vars n'ont
pas la même adress mémoire

# 19

In [89]:
a =  np.array([0, 1])
print("adress a: {}".format(id(a)))

b =  np.array([0, 1])
print("adress b: {}".format(id(b)))

c = a
print("adress c: {}".format(id(c)))

a += 1

print("val a: {0} \nval c: {1}".format(a, c))

adress a: 2063831821808
adress b: 2063832036576
adress c: 2063831821808
val a: [1 2] 
val c: [1 2]



- cette opération affecte la var ``c`` car les vars ont
 la même adress mémoire

# 20

In [97]:
# create vars
var_1 = 1
var_2 = 1

print("var_1 == var_2: {}".format(var_1 == var_2))
print("var_1 is var_2: {}".format(var_1 is var_2))

var_1 == var_2: True
var_1 is var_2: True


In [98]:
# create vars
var_1 = 1000
var_2 = 1000

print("var_1 == var_2: {}".format(var_1 == var_2))
print("var_1 is var_2: {}".format(var_1 is var_2))

var_1 == var_2: True
var_1 is var_2: False


- dans le 1er cas les deux vars ont même adresse
- dans le 2ème cas les deux vars n'ont pas la même adresse
- ``==`` fait un check sur les valeurs des variable, cependant ``is`` fait check sur l'adresse